name: Build for Windows ARM64

on:
  push:

jobs:
  build-windows-arm64:
    name: Build
    runs-on: ubuntu-24.04-arm
    env:
      llvm_path: "${{ github.workspace }}/llvm-mingw"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt update
          sudo apt search wine
          sudo apt install \
            build-essential p7zip cmake ninja-build pkg-config autoconf automake autoconf-archive make texlive-binaries texinfo bison flex m4 libtool wine wine64 wine-binfmt binfmt-support 
          uname -a 
          wget https://github.com/minnyres/aria2-windows-arm64/releases/download/v1.37.0/aria2_1.37.0_arm64.zip
          7z x  aria2_1.37.0_arm64.zip
          ls
          ./aria2c.exe https://github.com/minnyres/aria2-windows-arm64/releases/download/v1.37.0/aria2_1.37.0_arm64.zip
          
          
